name: Docker CI/CD Pipeline - KUCL

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kucl22:actions

  deploy:
    needs: build
    runs-on: [self-hosted, kucl22]

    steps:
      - name: Ensure SSH Key Permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.D_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Docker Image
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.S_USER }}@${{ secrets.D_HOST }} << 'EOF'
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kucl22:actions
            docker stop kucl_container || true
            docker rm kucl_container || true
            docker run -d --name kucl_container ${{ secrets.DOCKERHUB_USERNAME }}/kucl22:actions
          EOF
